site_name: CÁLCULO II - Tomás Caruso

theme:
  name: material
  font:
    text: Inter
    code: Inter
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
hooks:
  - hooks.py
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true # Esto solo envuelve la matemática en un <span> para que JS la encuentre

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js